set -g prefix M-Space
bind M-Space send-prefix

set -g status-style bg=color3,fg=color0
set -g pane-active-border-style fg=color4,bg=terminal

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
