unbind C-b

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'yanik-thurner/nvim-copy-mode'

set -g escape-time 5

set -g prefix C-Space
bind C-Space send-prefix

set -g set-clipboard on
set -g allow-passthrough on

bind -n M-h resize-pane -L 2
bind -n M-j resize-pane -D 2
bind -n M-k resize-pane -U 2
bind -n M-l resize-pane -R 2

bind -n M-H swap-pane -s '{left-of}'
bind -n M-J swap-pane -s '{down-of}'
bind -n M-K swap-pane -s '{up-of}'
bind -n M-L swap-pane -s '{right-of}'

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-n next-window
bind -n M-p previous-window

set -g base-index 1
set -g history-limit 5000

bind v split-window -h -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'
bind q set -p pane-active-border-style 'fg=white,bg=red' \; \
  confirm-before -p "kill '#{pane_current_command}' in #{window_name}:#{pane_index}? (y/n)" \
    "kill-pane" \; \
  set -pu pane-active-border-style

# Layout Undo
bind -r u select-layout -o


# Dim inactive panes
set -g window-style bg=terminal,fg=brightblack
set -g window-active-style bg=terminal,fg=terminal
set -g pane-border-style fg=brightblack,bg=terminal
set -g pane-active-border-style fg=color6,bg=terminal
set -g pane-border-indicators colour
set -g pane-border-lines single
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} "


if-shell '[ -n "$DOTFILES_REMOTE" ]' 'source $HOME/.config/tmux/tmux-remote.conf'

# ------------------------- #
run '$HOME/.config/tmux/plugins/tpm/tpm'
